extends: substitution
message: "Use '%s' instead of '%s'."
level: error
ignorecase: false
swap:
  "Github": "GitHub"
  "MacOS": "macOS"
  "MacOs": "macOS"
  "Macos": "macOS"
  "OpenMp": "OpenMP"
  "openMP": "OpenMP"
  "Powershell": "PowerShell"
  "Power Shell": "PowerShell"
  "conda forge": "conda-forge"
